# working directory is ABC-Enhancer-Gene-Prediction 

### INPUT DATA
# Add your inputs here
biosamplesTable: "config/config_biosamples_chr22.tsv"  # replace with your own config/config_biosamples.tsv

### OUTPUT DATA
predictions_results_dir: "results"


### REFERENCE FILES
ref:
        chrom_sizes: "reference/hg38/GRCh38_EBV.no_alt.chrom.sizes.tsv"
        regions_blocklist: "reference/hg38/GRCh38_unified_blacklist.bed"
        ubiquitous_genes: "reference/UbiquitouslyExpressedGenes.txt"
        genes: "reference/hg38/CollapsedGeneBounds.hg38.bed"
        genome_tss: "reference/hg38/CollapsedGeneBounds.hg38.TS500bp.bed"
        qnorm: "reference/EnhancersQNormRef.K562.txt"

### RULE SPECIFIC PARAMS
params_macs:
        pval: 0.1
        genome_size: hs  # shortcuts: hs: human ; mm: mice
        threads: 10

# These parameters are used to run the Run Candidate Regions portion of the abc code 
params_candidate:
        peakExtendFromSummit: 250
        nStrongestPeaks: 150000

# These parameters are used to run the Run Neighborhoods portion of the abc code
params_neighborhoods:
        use_qnorm: True
        
# These parameters are used to run the Predictions portion of the abc code
params_predict:
        flags: "--scale_hic_using_powerlaw"

params_filter_predictions:
        score_column: 'ABC.Score'
        threshold: .02
        include_self_promoter: True
        only_expressed_genes: False


### INTERNAL USE ONLY

# ABS path to prepend to reference and script files
# Only relevant when using ABC as a submodule
ABC_DIR_PATH: ""
