
# working directory where ABC repo is located 
working_dir: "/oak/stanford/groups/engreitz/Users/atan5133/"
# directory to output DHS/H3k27ac bam files and other output metadata files
# output_data_dir: "/oak/stanford/groups/engreitz/Users/kmualim/ENCODEData/bamfiles"

# directory to output ABC Predictions
predictions_results_dir: "/oak/stanford/groups/engreitz/Users/atan5133/2021_0606_ABC_newTSS"
# directory to average hic Predictions
hic_dir: "/oak/stanford/groups/engreitz/Users/atan5133/ABC-Enhancer-Gene-Prediction/example_chr22/input_data/HiC/raw/"
# directory with environments 
envs_dir: "/oak/stanford/groups/engreitz/Users/atan5133/ABC-Enhancer-Gene-Prediction/workflow/envs"
# directory with code
code_dir: "/oak/stanford/groups/engreitz/Users/atan5133/ABC-Enhancer-Gene-Prediction/workflow/scripts"
input_dir: "/oak/stanford/groups/engreitz/Projects/ABC/ABC_inputs"
biosamplesTable: "/oak/stanford/groups/engreitz/Users/atan5133/ABC-Enhancer-Gene-Prediction/config/config-biosamples-chr22.tsv"

# if input data is provided, generate and use cell-type specific TSS annotations 
use_altTSS: False

# parameters to determine whether to apply pooling + number of threads 
# leave blank if not applicable 
pooling_param: "--apply_pool"
threads: 10

params_macs:
        pval: 0.1
        threads: 10

# These parameters are used to run the Run Candidate Regions portion of the abc code 
params_candidate:
        DHS: False
        chrom_sizes: "/oak/stanford/groups/engreitz/Users/atan5133/ABC-Enhancer-Gene-Prediction/example_chr22/reference/chr22"
        regions_blocklist: "/oak/stanford/groups/engreitz/Projects/ABC/ReferenceFiles/wgEncodeHg19ConsensusSignalArtifactRegions.bed"
        genome_tss: "/oak/stanford/groups/engreitz/Projects/ABC/ReferenceFiles/RefSeqCurated.170308.bed.CollapsedGeneBounds.TSS.500bp.bed"
        alt_tss_dir: "/oak/stanford/groups/engreitz/Users/kmualim/ENCODEData/genome_tss/refseq_data"
        peakExtendFromSummit: 250
        nStrongestPeaks: 150000

# These parameters are used to run the Run Neighborhoods portion of the abc code
params_neighborhoods:
        ubiquitous_genes: "/oak/stanford/groups/engreitz/Projects/ABC/ReferenceFiles/UbiquitouslyExpressedGenesHG19.txt"
        qnorm: "/oak/stanford/groups/engreitz/Projects/ABC/ReferenceFiles/EnhancersQNormRef.K562.txt"
        genes: "/oak/stanford/groups/engreitz/Users/atan5133/ABC-Enhancer-Gene-Prediction/example_chr22/reference/RefSeqCurated.170308.bed.CollapsedGeneBounds.chr22.bed"

# These parameters are used to run the Predictions portion of the abc code
params_predict:
        hic_resolution: 5000
        scale_hic: "--scale_hic_using_powerlaw"
        threshold: 0.02
        all_putative: "--make_all_putative"
        self_promoter: "--include_self_promoter"
